spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    driver-class-name: org.postgresql.Driver
    username: compose-postgres
    password: compose-postgres

logging:
  level:
    org:
      hibernate:
        type: trace
