spring:
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    driver-class-name: org.postgresql.Driver
    username: compose-postgres
    password: compose-postgres
